name: Test supported versions

# Need the quotes, otherwise YAML.load, which we uses to generate run_tests_on_head.yml will interpret this
# as the boolean `true`...
'on':
  push:
    branches: [ issue ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - gemfile: gemfiles/rails_6_1.gemfile
            ruby_version: 2.7

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle config gemfile ${{ matrix.gemfile }}
        bundle install --jobs 4 --retry 3
        bundle env
        bundle exec rake test
